export const ADD_CHORD = 'ADD_CHORD';
export const CHANGE_ACTIVE_INDEX = 'CHANGE_ACTIVE_INDEX';
export const CHANGE_ROOT = 'CHANGE_ROOT';
export const CHANGE_ACCIDENTAL = 'CHANGE_ACCIDENTAL';
export const CHANGE_MODE = 'CHANGE_MODE';
export const CHANGE_TRI_NOTES = 'CHANGE_TRI_NOTES';
export const CHANGE_EXT_NOTES = 'CHANGE_EXT_NOTES';
